### ISSUE TITLE
halo2-scaffold has compile errors when using the community-edition branch of halo2-lib

### ISSUE THREAD

**Issue by notnotraju** [axiom-crypto/halo2-lib#63]
I updated my cargo.toml file in halo2-scaffold to use the community-edition of halo2-lib, and when I compiled I got the following error:

```error[E0277]: the trait bound `[u64; 4]: From<F>` is not satisfied
   --> src/scaffold/mod.rs:256:34
    |
256 |     fn synthesize(&self, config: Self::Config, layouter: impl Layouter<F>) -> Result<(), Error> {
    |                                  ^^^^^^^^^^^^ the trait `From<F>` is not implemented for `[u64; 4]`
    |
    = note: required for `F` to implement `Into<[u64; 4]>`
    = note: required for `F` to implement `halo2_base::utils::ScalarField`
note: required by a bound in `snark_verifier_sdk::halo2::aggregation::RangeWithInstanceConfig`
   --> /home/raju/.cargo/git/checkouts/snark-verifier-d84de59606f606ae/b162586/snark-verifier-sdk/src/halo2/aggregation.rs:156:39```

I get the same error re: ```type Config = RangeWithInstanceConfig<F>;``` and ```fn synthesize(&self, config: Self::Config, layouter: impl Layouter<F>) -> Result<(), Error> {```

**Comment by jonathanpwang** [comment]
This is because halo2-scaffold also uses snark-verifier and axiom-eth. Those branches are using other version of halo2-lib. In principle this can be solved with patching, but axiom-eth has not been updated to be compatible with changes in community-edition yet. I will update halo2-scaffold to community edition when that is resolved.

**Comment by jonathanpwang** [comment]
Fixed by https://github.com/axiom-crypto/halo2-scaffold/pull/5
